### ISSUE TITLE
Exporting the correct csv amplitude file from QX Manager v.1.2

### ISSUE THREAD

**Issue by monis4567** [HansPetterBrodal/PoDCall#1]
How can I in QX manager v1.2 export the correct csv amplitude file format? I can export a csv file (attached in weblinks), but I cannot get files like the ones associated with the package - like these
VIM_4Plex_A04_Amplitude.csv
VIM_4Plex_B04_Amplitude.csv
VIM_4Plex_D04_Amplitude.csv
VIM_4Plex_D05_Amplitude.csv
VIM_4Plex_H05_Amplitude.csv

I have added weblinks to my own exported '.csv' files, and the original '.ddpcr' files I have from the QX manager v1.2 software
https://www.dropbox.com/scl/fi/gutog8s85wxbp239ynq1d/ddpcr0035_Promin_20221124_20221124_083127_260.csv?rlkey=s8nir68mj4ip3wsf3gz42cru5&dl=0
https://www.dropbox.com/scl/fi/7siknfumg4xo31ct2nhlb/ddpcr0035_Promin_20221124_20221124_083127_260.ddpcr?rlkey=2swqaazhj1yb0t9k63glk1ja8&dl=0
https://www.dropbox.com/scl/fi/ohqx2hnln5l8d9x7o7vyx/ddpcr0017_Mnelei_20220908_105434_410.csv?rlkey=j951ismw6jxpsbjlc3jdg41f8&dl=0
https://www.dropbox.com/scl/fi/rz2yb8i8el250temmujbf/ddpcr0017_Mnelei_20220908_105434_410.ddpcr?rlkey=bihjdog8c3tt4ddvblqgb161o&dl=0

I am not sure what to choose from the drop down menus in QX manager v1.2  to get a '.csv' file that is  similar. 
Could you provide more details on how such files are generated from the QX manager v1.2?

I assume that I need a file format similar to the contents I can see in 'VIM_4Plex_H05_Amplitude.csv' . If I have misunderstood this part, could you then please show me how to read in the files from my weblink using PoDCall? 

I tried this in R v4.3

```
# define input file
inf01 <- "ddpcr0017_Mnelei_20220908_105434_410_wellID_amplitude.csv"
# ## Run PoDCall
thresholdTable <- PoDCall::podcallDdpcr(dataDirectory=inf01, 
                                         software="QX Manager")

```
Where the 'ddpcr0017_Mnelei_20220908_105434_410_wellID_amplitude.csv' file is the same as the '.csv'-file I have provided in the weblink above, apart from that I have changed the file name, since the vignette and tutorial (this one : https://bioconductor.org/packages/devel/bioc/vignettes/PoDCall/inst/doc/PoDCall.html) suggested this file ending.

**Comment by HansPetterBrodal** [comment]
Hi Steen,

QX manager v1.2 does unfortunately not have the functionality to export the amplitude files you need to run PoDCall.
You will have to upgrade to QX Manager v2.0, which to my understanding is free of charge since you already have v1.2.

In version 2.0 you will find the option here:
***@***.***

Beware that you might have to change some settings on your computer regarding decimal separator.
QX Manager does not yet let you choose what decimal separator to use and will use the systems default decimal separator, which is usually a comma in the Nordic countries.
To change this, go to control panel and settings for region and language and change decimal separator to . if it is anything else.

Lastly, the argument “dataDirectory” for the function “podcallDdpcr” should be the path to the directory that contains the amplitude files for each well, not individual amplitude files.

I hope this helps!

Best regard,
Hans Petter Brodal

From: steen knudsen ***@***.***
Sent: 19. januar 2024 11:16
To: HansPetterBrodal/PoDCall
Cc: Subscribed
Subject: [HansPetterBrodal/PoDCall] Exporting the correct csv amplitude file from QX Manager v.1.2 (Issue #1)


How can I in QX manager v1.2 export the correct csv amplitude file format? I can export a csv file (attached in weblinks), but I cannot get files like the ones associated with the package - like these
VIM_4Plex_A04_Amplitude.csv
VIM_4Plex_B04_Amplitude.csv
VIM_4Plex_D04_Amplitude.csv
VIM_4Plex_D05_Amplitude.csv
VIM_4Plex_H05_Amplitude.csv

I have added weblinks to my own exported '.csv' files, and the original '.ddpcr' files I have from the QX manager v1.2 software
https://www.dropbox.com/scl/fi/gutog8s85wxbp239ynq1d/ddpcr0035_Promin_20221124_20221124_083127_260.csv?rlkey=s8nir68mj4ip3wsf3gz42cru5&dl=0
https://www.dropbox.com/scl/fi/7siknfumg4xo31ct2nhlb/ddpcr0035_Promin_20221124_20221124_083127_260.ddpcr?rlkey=2swqaazhj1yb0t9k63glk1ja8&dl=0
https://www.dropbox.com/scl/fi/ohqx2hnln5l8d9x7o7vyx/ddpcr0017_Mnelei_20220908_105434_410.csv?rlkey=j951ismw6jxpsbjlc3jdg41f8&dl=0
https://www.dropbox.com/scl/fi/rz2yb8i8el250temmujbf/ddpcr0017_Mnelei_20220908_105434_410.ddpcr?rlkey=bihjdog8c3tt4ddvblqgb161o&dl=0

I am not sure what to choose from the drop down menus in QX manager v1.2 to get a '.csv' file that is similar.
Could you provide more details on how such files are generated from the QX manager v1.2?

I assume that I need a file format similar to the contents I can see in 'VIM_4Plex_H05_Amplitude.csv' . If I have misunderstood this part, could you then please show me how to read in the files from my weblink using PoDCall?

I tried this in R v4.3

# define input file

inf01 <- "ddpcr0017_Mnelei_20220908_105434_410_wellID_amplitude.csv"

# ## Run PoDCall

thresholdTable <- PoDCall::podcallDdpcr(dataDirectory=inf01,

                                         software="QX Manager")



Where the 'ddpcr0017_Mnelei_20220908_105434_410_wellID_amplitude.csv' file is the same as the '.csv'-file I have provided in the weblink above, apart from that I have changed the file name, since the vignette and tutorial (this one : https://bioconductor.org/packages/devel/bioc/vignettes/PoDCall/inst/doc/PoDCall.html) suggested this file ending.

**Comment by monis4567** [comment]
Thanks. I got QX Manager v2.0. This worked getting the amplitude csv files.  In R v4.3 I then tried
```

thresholdTable <- PoDCall::podcallDdpcr(dataDirectory=ind_01, 
                                         software="QX Manager",
                                         ch2=F)

```
Where 'ind_01' is the input directory that holds all the files in this compressed in this tar.gz archive
https://www.dropbox.com/scl/fi/tkbpjsftjultep7ugqim5/ddpcr0023_Psefar.tar.gz?rlkey=irddi6f17qpwy160dbr5g33i6&dl=0

But this throws me this error

> thresholdTable <- PoDCall::podcallDdpcr(dataDirectory=ind_01, 
+                                          software="QX Manager",
+                                          ch2=F)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In FUN(X[[i]], ...) :

I am not sure why, as another directory with amplitude files - here compressed in this tar.gz archive 

https://www.dropbox.com/scl/fi/xfjwg0u1x2o5uxpyw9871/ddpcr0017_Mnelei.tar.gz?rlkey=cjy9vw9z9pwn18d8gkpnqxc50&dl=0

works just fine.

Would you be able to spot what I am doing wrong?

**Comment by HansPetterBrodal** [comment]
Hi again, Steen

The error you get is caused by a couple of the files (A02, C02, D02 in ddpcr0023_Psefar) that have no droplets, only header.
Did you in any way edit the files you exported from QX Manager 2.0 before you tried to analyze them?
The reason I ask is because the files we get in our lab when exporting from QX Manager have four extra lines
in the beginning of each file that we make PoDCall skip (see picture of how it looks like under).
When there are no lines in the files to skip, as in your files mentioned earlier, R throws an error.

***@***.***

When using the older QuantaSoft, these lines were not there, and that is really the only reason we ask users to specify QuantaSoft or QX Manager.
If your files never have the extra four lines and they automatically look like the ones you shared, you can set software=”Quanta Soft” and it should run fine.

The example files included in PoDCall were exported with QuantaSoft, and we should perhaps make users better aware of this.

Thank you again for reaching out, I hope this gets you on your way with the analysis!

Best regards,
Hans Petter Brodal

**Comment by monis4567** [comment]
Thanks. This made it work. Yes, I modified the amplitude csv files from the QX manager v2.0 before trying to read them in R. The output amplitude files had a comma as a decimal separator, and this introduced too many columns for R to read in. I ended up writing a bash code I could use for modifying the amplitude csv input files. The bash code also checks for amplitude files that has no data, and adds '0,0,0' , so that the amplitude file at least has a single line of data. 
The bash code I used for modifying is here below. Feel free to use it or modify it to something more elegant.
```

#!/bin/bash
# -*- coding: utf-8 -*-

##get the present directory
WD=$(pwd)

INDIR1="amplitude_data_from_QX_manager_v2"
TMPDIR="tmp_dir"

#remove the old versions of the in- and output directory
rm -rf ${TMPDIR}
#make new versions of the in- and output directory
#mkdir ${TMPDIR}

cd "$WD"/"$INDIR1"
# make a list that holds the prefix to the names of the ddpcr csv report files
LSSMPL=$(ls | cut -d'_' -f1-2 | uniq | grep 'dd')

#make the list of samples an array you can iterate over
declare -a SMPLARRAY=("${LSSMPL}")

#iterate over prefix to the names of the ddpcr csv reports
# and make new directories and copy files in to these directories 
for D in ${SMPLARRAY[@]}
do
	echo "$D"
	rm -rf "$WD"/"$D"
	mkdir "$WD"/"$D"
	#
	F=$(ls | grep "${D}")
	# notice that $F needs to have no quotation marks around it
	# see this question: https://unix.stackexchange.com/questions/405527/i-get-message-file-name-too-long-when-running-for-in-and-touch
	for file in $F
		do
		#echo $file
		# # this question : https://stackoverflow.com/questions/42004482/shell-script-replace-a-specified-column-with-sed
		# replace in lines in file to get point as delimeter between 1st and 2nd comma separated element
		# and btween 3rd and 4th comma separated element
		cat "$file" | awk 'BEGIN {FS=","; OFS=""} {print $1,".",$2,",",$3,".", $4,",",$5}' | \
		sed -e 's:1Amplitude\.Ch2Amplitude:1Amplitude,Ch2Amplitude:g' | \
		sed 's/\r//' | \
		LC_ALL=C sed -e 's/\r$//' | \
		sed 's/\.,//g' > "$WD"/"$D"/"$file"
		# To SKIP the first N lines:
		# https://stackoverflow.com/questions/604864/print-a-file-skipping-the-first-x-lines-in-bash
		# tail -n +5 > "$WD"/"$D"/"$file"
		# #sed ':a;N;$!ba;s/\n//g' 
		#cp $file "$WD"/"$D"/.
		#cat "$file" | head -3

		#check the last line of the output file
		lastline=$(tail -1 "$WD"/"$D"/"$file")
		if [[ "$lastline" = *Amplitude* ]]; then
			#echo "$file"
			#echo "$lastline"
			echo "0,0,0" >> "$file"
		fi
		
		done 
done


```
